# Development profile.

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/lms_vera
spring.datasource.username=postgres
spring.datasource.password=2707
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
