package vera.lms.enums;

public enum AuditAction {
    USER_CREATED,
    USER_STATUS_UPDATED,
    PASSWORD_RESET,
    ENROLLMENT_EXTENDED,
    LESSON_PUBLISHED,
    LESSON_ARCHIVED,
    LESSON_DELETED,
    TEACHER_REVIEW_SUBMITTED,
    CHECKPOINT_RESULT_SUBMITTED,
    FINAL_ASSESSMENT_RESULT_SUBMITTED
}
